- name: Creates the database and tables for the benchmark
  hosts: localhost
  roles:
    - role: '../roles/project_directories'
    - role: '../roles/benchmark'
    - role: '../roles/tezos'
    - role: '../roles/clickhouse'
  vars_prompt:
    - name: passw_clickhouse_user
      prompt: "Provide the password for the clickhouse user: '{{ database_user }}'"

  tasks:
    - name: Create the clickhouse database
      block:
        - name: Check if the clickhouse-server is started / running
          ansible.builtin.service:
            name: clickhouse-server
            state: started
          become: true

        - name: Pause for 3 seconds to start the clickhouse-server
          ansible.builtin.pause:
            seconds: 3

        - name: "Create Clickhouse Database : '{{ database_name }}'"
          ansible.builtin.command:
            cmd: clickhouse-client --password {{ passw_clickhouse_user }} --query="CREATE DATABASE IF NOT EXISTS {{ database_name }}"
          register: create_result
          changed_when: create_result != ""

        - name: Show Databases
          ansible.builtin.command:
            cmd: clickhouse-client --password {{ passw_clickhouse_user }} --query="SHOW DATABASES"
          register: show_result
          changed_when: show_result != ""

        - name: Show Databases
          ansible.builtin.debug:
            msg: "{{ show_result.stdout_lines }}"

    - name: Create all tables for the different logs
      block:
        - name: "Create Clickhouse tables: protocol_constants, vm_hardware_properties, experiment_vars "
          include_tasks: ./tasks/task-create_table.yaml
          vars:
            primary_keys: "name_of_chain, ts_creation_of_protocol"
          loop:
            - "protocol_constants"
            - "vm_hardware_properties"
            - "experiment_vars"
          loop_control:
            loop_var: table_name

        - name: "Create Clickhouse tables: endorsements, blocks "
          include_tasks: ./tasks/task-create_table.yaml
          vars:
            primary_keys: "name_of_chain, block_level, block_hash"
          loop:
            - "endorsements"
            - "blocks"
          loop_control:
            loop_var: table_name

        - name: "Create Clickhouse tables: operations"
          include_tasks: ./tasks/task-create_table.yaml
          vars:
            primary_keys: "name_of_chain, op_send_rate_lvl, op_first, op_last, op_hash"
          loop:
            - "operations"
          loop_control:
            loop_var: table_name

        - name: "Create Clickhouse tables: sys_logs"
          include_tasks: ./tasks/task-create_table.yaml
          vars:
            primary_keys: "name_of_chain, hostname, datetime_u"
          loop:
            - "system_log_cpl"
            - "system_log_cpu"
            - "system_log_dsk"
            - "system_log_mem"
            - "system_log_net_upper"
            - "system_log_net"
            - "system_log_prc"
            - "system_log_prd"
            - "system_log_prm"
            - "system_log_psi"
          loop_control:
            loop_var: table_name
