- name: Install Docker
  hosts: all
  become: true

  tasks:
    - name: Install aptitude using apt
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true
        force_apt_get: true

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - lsb-release
          - python3-pip
        update_cache: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: true

    - name: Install python sdk
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
