---
- name: Install Tezos
  hosts: all

  tasks:
    - name: Install aptitude using apt
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true
        force_apt_get: true
      become: true

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https=2.0.9 # 2.0.6
          - ca-certificates=20211016~20.04.1
          - curl=7.68.0-1ubuntu2.13
          - gnupg-agent=2.2.19-3ubuntu2.2
          - software-properties-common=0.99.9.8
          - lsb-release=11.1.0ubuntu2
          - python3-pip=20.0.2-5ubuntu1.6
        state: present
        update_cache: true
        allow_downgrade: true
      become: true

    - name: Create tezos-software directory
      ansible.builtin.file:
        path: "/home/ubuntu/tezos-software/"
        state: directory
        mode: '0777'

    - name: Copy and extract tezos_software_v12-3.tar.gz
      ansible.builtin.unarchive:
        src: "{{ git_project_dir }}/tezos-software/tezos_software_v12-3.tar.gz"
        dest: "/home/ubuntu/"
        mode: '0777'

    - name: Install Tezos v12.3 with pthangz2
      ansible.builtin.apt:
        deb: /home/ubuntu/tezos-software/{{ item }}
      loop:
        - tezos-sapling-params_8.2-0ubuntu4~focal_amd64.deb
        - tezos-client_12.3-0ubuntu1~focal_amd64.deb
        - tezos-node_12.3-0ubuntu1~focal_amd64.deb
        - tezos-accuser-011-pthangz2_12.3-0ubuntu1~focal_amd64.deb
        - tezos-baker-011-pthangz2_12.3-0ubuntu1~focal_amd64.deb
        - tezos-endorser-011-pthangz2_12.3-0ubuntu1~focal_amd64.deb
      become: true

    - name: Delete tezos-installation directory
      ansible.builtin.file:
        path: "/home/ubuntu/tezos-software"
        state: absent
...
