---
#  Tasks to:
#  1. Run the python script: "reveal_pubkey" to reveal the worker account's public keys in order to be able to send transactions from the worker accounts.
#  2. Time the total execution of the python script on all nodes.
#  -- Provide vars: scripts_dir, client_dir, log_dir, accounts_dir, workload_dir, minimal_block_delay, chain_name --

- name: Start of timing
  block:
    - name: Retrieve system date and time (_unix epoch)
      ansible.builtin.command: date +%Y-%m-%dT%H:%M:%S.%5N_%s.%6N
      register: ch_system_datetime
      changed_when: ch_system_datetime.stdout_lines != ""

    - name: Set CH system time as unix epoch
      ansible.builtin.set_fact:
        "ch_ts_epoch_start_{{ chain_name }}": "{{ ch_system_datetime.stdout[26:] }}"
  delegate_to: localhost
  run_once: true


- name: "Run python script to reveal the public key of each baker account in order to send transcations"
  ansible.builtin.command:
    cmd: "python3 {{ scripts_dir }}/reveal_pubkey.py {{ client_dir }} {{ log_dir }} {{ accounts_dir }} \
    {{ workload_dir }} {{ inventory_hostname }} {{ reveal_log }} {{ tezos_rpc_port }}"
  when: async_force
  async: "{{ max_retries }}"
  poll: 0
  register: reveal_result
