---
#  Tasks to:
#  1. Run the python script: "distribute_funds" to distribute the necessary funds from the baker accounts to the worker accounts
#  2. Time the total execution of the python script on all nodes.
#  -- Provide vars: baker_account_name, scripts_dir, client_dir, log_dir, accounts_dir, workload_dir, chain_name --

- name: Start of timing
  block:
    - name: Retrieve system date and time (_unix epoch)
      ansible.builtin.command: date +%Y-%m-%dT%H:%M:%S.%5N_%s.%6N
      register: ch_system_datetime
      changed_when: ch_system_datetime.stdout_lines != ""

    - name: Set CH system time as unix epoch
      ansible.builtin.set_fact:
        "ch_ts_epoch_start_{{ chain_name }}": "{{ ch_system_datetime.stdout[26:] }}"
  delegate_to: localhost
  run_once: true


- name: "Run python script to distribute funds from baker to worker accounts"
  ansible.builtin.command:
    cmd: "python3 {{ scripts_dir }}/distribute_funds.py {{ baker_account_name }} {{ client_dir }} {{ log_dir }} {{ accounts_dir }} \
    {{ workload_dir }} {{ inventory_hostname }} {{ dist_funds_log }} {{ tezos_rpc_port }}"
  when: async_force
  async: "{{ max_retries }}"
  poll: 0
  register: distribution_result
