---
#  Tasks to:
#  1. Stop the timing of script execution and display the time period
#  -- Provide vars: chain_name_item  --
- name: Calculate and display execution time of script
  block:
    - name: Retrieve system date and time (_unix epoch)
      ansible.builtin.command: date +%Y-%m-%dT%H:%M:%S.%5N_%s.%6N
      register: ch_system_datetime
      changed_when: ch_system_datetime.stdout_lines != ""

    - name: Display time to execute
      ansible.builtin.debug:
        msg: "{{ chain_name_item }} -- Time to {{ event }}: \
        {{ ch_system_datetime.stdout[26:] | int - lookup('vars', 'ch_ts_epoch_start_' + chain_name_item) | int }} seconds"
        verbosity: 0
  delegate_to: localhost
  run_once: true
