---
# Tasks to import the secret key to tezos-client

# -- Provide vars: client_dir, baker_account_name, baker_accounts --

- name: Set secret key of baker account
  ansible.builtin.set_fact:
    secret_key_boot: "{{ baker_accounts['baker_account_' + inventory_hostname.split('_')[1]]['secret_key'] }}"

- name: Import secret key to tezos-client {{ inventory_hostname }}
  ansible.builtin.command:
    cmd: tezos-client -d {{ client_dir }} import secret key {{ baker_account_name }} unencrypted:{{ secret_key_boot | quote }} -f
  register: import_b_acc
  changed_when: import_b_acc.stdout_lines != ""
- name: Print import status of baker account
  ansible.builtin.debug:
    msg: "{{ import_b_acc.stdout_lines }}"
    verbosity: 1
