---
#  Tasks to import secret key from baker accounts to tezos-client

#  -- Provide vars: client_dir, chain_name, baker_account_name, baker_accounts, new_b_accounts --

- name: Read account files, save to var and (print)
  block:
    - name: Save baker accounts from file to baker_accounts
      ansible.builtin.include_vars:
        file: "{{ experiments_dir }}/{{ chain_name }}/accounts/{{ chain_name }}_baker_accounts.json"
        name: baker_accounts

    - name: Save genesis account from file to genesis_account
      ansible.builtin.include_vars:
        file: "{{ experiments_dir }}/{{ chain_name }}/accounts/{{ chain_name }}_genesis_account.json"
        name: genesis_account
      when: inventory_hostname in groups['group_genesis_' + chain_name]

- name: Import secret key of genesis account to node 1 / group genesis node
  block:
    - name: Import genesis secret key to tezos-client
      ansible.builtin.command:
        cmd: tezos-client -d {{ client_dir }} import secret key genesis unencrypted:{{ genesis_account.secret_key }} -f
      register: import_gen
      changed_when: import_gen.stdout_lines != ""
    - name: Print import status of genesis account
      ansible.builtin.debug:
        msg: "{{ import_gen.stdout_lines }}"
        verbosity: 1
  when: inventory_hostname in groups['group_genesis_' + chain_name]

- name: Import baker accounts to clients
  tags: new_baker_accounts
  block:
    - name: Import secret key of baker accounts into clients
      include_tasks: ./task-import_secret_key_baker.yaml
  when:
    - inventory_hostname in groups['group_bakers_' + chain_name]
